<?php

/**
 * @file
 */

/**
 * Implements hook_form_alter().
 */
function drsneolimp_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
 switch ($form_id) {
   case 'node_news_form':
   case 'node_news_edit_form':
     $form['#prefix'] = '<div id="form-wrapper">';
     $form['#suffix'] = '</div>';

     $form['field_news_type']['widget']['#ajax'] = [
       'callback' => 'news_type_change',
       'wrapper' => 'form-wrapper',
       'event' => 'change',
     ];

     $form['field_date_range']['#states'] = [
       'visible' => [
         ':input[name="field_news_type"]' => ['value' => 'announcements'],
       ],
     ];
     break;
 }
}
function news_type_change($form, \Drupal\Core\Form\FormStateInterface &$form_state) {
  return $form;
}
