<?php

/**
 * @file
 */

/**
 * Implements hook_form_alter().
 */
function drsneolimp_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
 switch ($form_id) {
   case 'node_news_form':
   case 'node_news_edit_form':
     $form['#prefix'] = '<div id="form-wrapper">';
     $form['#suffix'] = '</div>';

     $form['field_news_type']['widget']['#ajax'] = [
       'callback' => 'news_type_change',
       'wrapper' => 'form-wrapper',
       'event' => 'change',
     ];

     $form['field_date_range']['#states'] = [
       'visible' => [
         ':input[name="field_news_type"]' => ['value' => 'announcements'],
       ],
     ];
     break;

    case 'views_exposed_form':
      if (isset($form['field_sport_kinds_target_id'])) {
        $form['field_sport_kinds_target_id']['#options']['All'] = t("All news");
      }
      break;
 }
}

function news_type_change($form, \Drupal\Core\Form\FormStateInterface &$form_state) {
  return $form;
}

function drsneolimp_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'drsneolimp/drsneolimp';
}
